clone_depth: 50

init:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')

install:
  - ps: Install-Product node $env:nodejs_version
  - npm cache clear --force
  - ps: >-
      if ($env:nodejs_version -eq "4") {
        npm install npm@latest-5 -g
      } else {
        npm install npm@latest -g
      }
  - npm --version
  - npm install -g bats

build: false

test_script:
  - bash -c 'bats test'
